apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: kube-controller-manager
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
    - name: raw-internal
      version: "0.0.1-snapshot"
    - name: kube-controller-manager
      version: "0.0.1-snapshot-kubernetes"
