apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      openshift.io/run-level: "0"
    name: openshift-core-operators

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: kubecontrollermanageroperatorconfigs.kubecontrollermanager.operator.openshift.io
  spec:
    scope: Cluster
    group: kubecontrollermanager.operator.openshift.io
    version: v1alpha1
    names:
      kind: KubeApiserverOperatorConfig
      plural: kubecontrollermanageroperatorconfigs
      singular: kubecontrollermanageroperatorconfig
    subresources:
      status: {}

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: system:openshift:operator:cluster-kube-controller-manager-operator
  roleRef:
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    namespace: openshift-core-operators
    name: openshift-cluster-kube-controller-manager-operator

- apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: openshift-core-operators
    name: openshift-cluster-kube-controller-manager-operator-config
  data:
    config.yaml: |
      apiVersion: operator.openshift.io/v1alpha1
      kind: GenericOperatorConfig

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: openshift-core-operators
    name: openshift-cluster-kube-controller-manager-operator
    labels:
      app: openshift-cluster-kube-controller-manager-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: openshift-cluster-kube-controller-manager-operator
    template:
      metadata:
        name: openshift-cluster-kube-controller-manager-operator
        labels:
          app: openshift-cluster-kube-controller-manager-operator
      spec:
        serviceAccountName: openshift-cluster-kube-controller-manager-operator
        containers:
        - name: operator
          image: openshift/origin-cluster-kube-controller-manager-operator:latest
          imagePullPolicy: IfNotPresent
          command: ["cluster-kube-controller-manager-operator", "operator"]
          args:
          - "--config=/var/run/configmaps/config/config.yaml"
          - "-v=4"
          volumeMounts:
          - mountPath: /var/run/configmaps/config
            name: config
        volumes:
        - name: serving-cert
          secret:
            defaultMode: 400
            secretName: openshift-cluster-kube-controller-manager-operator-serving-cert
            optional: true
        - name: config
          configMap:
            defaultMode: 440
            name: openshift-cluster-kube-controller-manager-operator-config

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: openshift-core-operators
    name: openshift-cluster-kube-controller-manager-operator
    labels:
      app: openshift-cluster-kube-controller-manager-operator

- apiVersion: kubecontrollermanager.operator.openshift.io/v1alpha1
  kind: KubeApiserverOperatorConfig
  metadata:
    name: instance
  spec:
    managementState: Managed
    imagePullSpec: openshift/origin-hypershift:latest
    version: 3.11.0
    logging:
      level: 4
    replicas: 2
