apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-kube-controller-manager
  name: controller-manager
  labels:
    app: openshift-kube-controller-manager
    controller-manager: "true"
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: openshift-kube-controller-manager
      controller-manager: "true"
  template:
    metadata:
      name: openshift-kube-controller-manager
      labels:
        app: openshift-kube-controller-manager
        controller-manager: "true"
    spec:
      serviceAccountName: openshift-kube-controller-manager-sa
      containers:
      - name: controller-manager
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["hypershift", "openshift-kube-controller-manager"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
      volumes:
      - name: config
        configMap:
          name: deployment-controller-manager-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: Exists
