apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
    openshift.io/cluster-monitoring: "true"
  name: openshift-kube-controller-manager
  labels:
    openshift.io/run-level: "0"
