apiVersion: v1
kind: Secret
metadata:
  name: service-account-private-key
  namespace: kube-system
  labels:
    tier: "control-plane"
    k8s-app: "kube-controller-manager"
    openshift.io/control-plane: "true"
    openshift.io/component: "controller"
data:
  service-account.key: |
    {{ .Assets | load "service-account.key" | indent 4 }}
