apiVersion: v1
kind: Secret
metadata:
  name: cluster-signing-ca
    namespace: kube-system
  labels:
    tier: "control-plane"
    k8s-app: "kube-controller-manager"
    openshift.io/control-plane: "true"
    openshift.io/component: "controller"
data:
  kube-ca.key: |
    {{ .Assets | load "kube-ca.key" | indent 4 }}
  kube-ca.crt: |
    {{ .Assets | load "kube-ca.crt" | indent 4 }}

