apiVersion: v1
kind: ConfigMap
metadata:
  name: client-ca
  namespace: kube-system
  labels:
    tier: "control-plane"
    k8s-app: "kube-controller-manager"
    openshift.io/control-plane: "true"
    openshift.io/component: "controller"
data:
  ca-bundle.crt: |
    {{ .Assets | load "kube-ca.crt" | indent 4 }}

