apiVersion: v1
kind: Secret
metadata:
  name: cluster-signing-ca
  namespace: {{ .Namespace }}
data:
  kube-ca.key: {{ .Assets | load "kube-ca.key" | base64 }}
  kube-ca.crt: {{ .Assets | load "kube-ca.crt" | base64 }}

